export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SET_UPLOADDATA = 'SET_UPLOADDATA'

export const SET_USERID = 'SET_USERID'

export const SET_SERIALNUMBER = 'SET_SERIALNUMBER'

export const SET_PART = 'SET_PART'

